// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc: v1.27.0
// source: users.sql

package sqlc

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, dob)
VALUES ($1, $2)
RETURNING id, name, dob
`

type CreateUserParams struct {
	Name string    `json:"name"`
	Dob  time.Time `json:"dob"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Dob)
	var user User
	err := row.Scan(&user.ID, &user.Name, &user.Dob)
	return user, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var deletedID int32
	err := row.Scan(&deletedID)
	return deletedID, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, dob
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var user User
	err := row.Scan(&user.ID, &user.Name, &user.Dob)
	return user, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, dob
FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	users := []User{}
	for rows.Next() {
		var user User
		if err := rows.Scan(&user.ID, &user.Name, &user.Dob); err != nil {
			return nil, err
		}
		users = append(users, user)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return users, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2,
    dob = $3
WHERE id = $1
RETURNING id, name, dob
`

type UpdateUserParams struct {
	ID   int32     `json:"id"`
	Name string    `json:"name"`
	Dob  time.Time `json:"dob"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.Dob)
	var user User
	err := row.Scan(&user.ID, &user.Name, &user.Dob)
	return user, err
}
